import type { Certificate } from "../types/cert";
import { pub } from "./paths";

export const CERTS: Certificate[] = [
  {
    id: "ssafy-1",
    title: "삼성청년SW·AI아카데미(SSAFY)",
    issuer: "삼성전자",
    category: "course",
    startDate: "2024-07-02",
    endDate:   "2025-06-30",
    issueDate: "2025-06-24",
    skills: ["Python", "Spring Boot", "Django", "FastAPI", "CS/알고리즘", "팀 프로젝트"],
    tags: ["course"],
    previewUrl: pub("certs/ssafy.png"),
  },
  {
    id: "ssafy-2",
    title: "우수상-빅데이터(분산)",
    issuer: "삼성전자",
    category: "course",
    startDate: "2025-02-24",
    endDate:   "2025-04-11",
    issueDate: "2025-04-11",
    skills: ["Spring Boot", "FastAPI", "Elasticsearch", "Hadoop", "Spark", "Kafka"],
    tags: ["award"],
    previewUrl: pub("certs/ExcellenceAward.png"),
  },
  {
    id: "ssafy-2",
    title: "최우수상",
    issuer: "삼성전자",
    category: "course",
    startDate: "2024-11-18",
    endDate:   "2024-11-29",
    issueDate: "2024-11-29",
    skills: ["Python", "Django", "Vue", "AWS"],
    tags: ["award"],
    previewUrl: pub("certs/GrandPrize.png"),
  },
  {
    id: "ipe-2024",
    title: "정보처리기사",
    issuer: "한국산업인력공단",
    category: "license",
    issueDate: "2024-06-18",
    previewUrl: pub("certs/ipe.pdf"),
  },
  {
    id: "sqld-2023",
    title: "SQLD (SQL 개발자)",
    issuer: "한국데이터산업진흥원",
    category: "license",
    issueDate: "2023-10-06",
    tags: ["award"],
    credentialId: "SQLD-050018366",
    previewUrl: pub("certs/sqld.pdf"),
  },
  {
    id: "gjaischool-1",
    title: "인공지능사관학교 - AI기반 웹서비스(Spring)",
    issuer: "광주인공지능사관학교",
    category: "course",
    startDate: "2023-06-07",
    endDate:   "2023-11-28",
    issueDate: "2023-11-28",
    skills: ["Java", "Spring Boot", "ML", "RL", "MySQL", "팀 프로젝트"],
    tags: ["course"],
    previewUrl: pub("certs/gwaischool.jpg"),
  },
  {
    id: "aiproject-1",
    title: "AI 융합프로젝트 교육사업 - 딥러닝 기반 호감도 개발 프로젝트",
    issuer: "인공지능산업융합사업단",
    category: "course",
    startDate: "2022-07-18",
    endDate:   "2022-11-30",
    issueDate: "2022-11-30",
    skills: ["Android", "AI", "팀 프로젝트"],
    tags: ["course"],
    previewUrl: pub("certs/aiproject.pdf"),
  },
];
